/**:
  ros__parameters:
    preprocessing:
      ransac:
        max_iteration: 1000
        voxel_grid_size: 0.05
        distance_threshold: 0.1
      clip_wall_pointcloud:
        max_iteration: 100
        max_correspondence_distance: 100.0
        transformation_epsilon: 1.0e-10
        euclidean_fitness_epsilon: 0.001
        clipping_threshold: 0.1

    grid_search:
      x_range_max: 0.075
      x_range_min: -0.075
      x_range_resolution: 0.025
      y_range_max: 0.075
      y_range_min: -0.075
      y_range_resolution: 0.025
      z_range_max: 0.05
      z_range_min: -0.05
      z_range_resolution: 0.025
      roll_range_max: 0.4
      roll_range_min: -0.4
      roll_range_resolution: 0.2
      pitch_range_max: 0.4
      pitch_range_min: -0.4
      pitch_range_resolution: 0.2
      yaw_range_max: 0.8
      yaw_range_min: -0.8
      yaw_range_resolution: 0.2
      maximum_iteration: 1000
      max_correspondence_distance: 100.0
      transformation_epsilon: 1.0e-10
      euclidean_fitness_epsilon: 0.001

    map_based_calibrator:
      debug_pub: true
